events {}

http {
    server {
        listen 80;

        location /app/ {
            proxy_pass http://react/;
        }

        location /legacy/ {
            proxy_pass http://apache/;
        }

        location /api/ {
            proxy_pass http://backend:5000/;
        }

    }
}